# Generated by Django 4.0.4 on 2022-05-12 06:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3f3b299f-bf5c-4ef6-897f-ecb04b018933'), primary_key=True, serialize=False)),
                ('is_important', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[(0, 'Активнo'), (1, 'Отложенo'), (2, 'Выполненo')], default=0, max_length=30)),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2022, 5, 13, 9, 56, 15, 635284))),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
