# Generated by Django 4.0.4 on 2022-05-27 12:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_important', models.BooleanField(default=False, verbose_name='Важно')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Активнo'), (1, 'Отложенo'), (2, 'Выполненo')], default=0)),
                ('inner', models.TextField(verbose_name='Текст заметки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2022, 5, 28, 15, 49, 28, 980963), verbose_name='Дата публикации')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments.Comment.note+', to='comments.comment')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
