# Generated by Django 4.0.4 on 2022-05-12 11:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='inner',
            field=models.TextField(default='sdfsdfsdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30466655-212b-4a87-a7ff-741fd733bd3a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 14, 36, 50, 450652)),
        ),
    ]
