# Generated by Django 4.0.4 on 2022-05-14 18:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0002_note_inner_alter_note_id_alter_note_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a1bc927-4b97-4fc8-a15b-08e1bd5e81f9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 21, 24, 38, 404132)),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(choices=[(0, 'Активнo'), (1, 'Отложенo'), (2, 'Выполненo')], default=(0, 'Активнo'), max_length=30),
        ),
    ]
