# Generated by Django 4.0.4 on 2022-05-14 18:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0003_alter_note_id_alter_note_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.UUID('888f5ca5-0902-4483-979b-6c29a11d4a24'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 21, 28, 46, 20523)),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.CharField(choices=[('Активнo', 0), ('Отложенo', 1), ('Выполненo', 2)], default=0, max_length=30),
        ),
    ]
