# Generated by Django 4.0.4 on 2022-05-14 18:29

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0004_alter_note_id_alter_note_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 21, 29, 9, 122168)),
        ),
    ]
