# Generated by Django 4.0.4 on 2022-05-14 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0006_alter_note_publication_date_alter_note_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 21, 31, 20, 77359)),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[('Активнo', 0), ('Отложенo', 1), ('Выполненo', 2)], default=0),
        ),
    ]
