# Generated by Django 4.0.4 on 2022-05-21 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note_api', '0007_alter_note_publication_date_alter_note_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='note',
            name='inner',
            field=models.TextField(verbose_name='Текст заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Важно'),
        ),
        migrations.AlterField(
            model_name='note',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 14, 52, 19, 721256), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='note',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Активнo'), (1, 'Отложенo'), (2, 'Выполненo')], default=0),
        ),
    ]
